apiVersion: v1
kind: Service 
metadata:
  name: vprormq-svc # name of the service 
spec:
  ports:
    - port: 15672 # port on which this service target and forward the request on container pod
      targetPort: vprormq-port # name of the container port which contain port value
      protocol: TCP
  selector:
    app: vprormq # only pod with a label of vprodb should access this service
  type: ClusterIP # service type will be cluster ip